name: CI

on:
  push:
    paths:
    - '**.kt'
    - '**.kts'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up GraalVM/Java 14
        uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.3.java11'
      - name: Build with Gradle
        run: git submodule update --init --recursive && ./gradlew test --stacktrace