name: CI

on:
  push:
    paths:
    - '**.kt'
    - '**.kts'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up GraalVM/Java 11
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
      - name: Build with Gradle
        run: |
          git submodule update --init --recursive
          ./gradlew test --stacktrace